### ISSUE TITLE
Add Readme File & Contributing File

### ISSUE THREAD

**Issue by Prathamesh-Shanbhag** [sakshipuranik23/clim8#5]

**Comment by Prathamesh-Shanbhag** [comment]
Also add your API Keys inside the Env Variables section on vercel so that your app stays deployed on Vercel

**Comment by sakshipuranik23** [comment]
Oh thank you so much! I'll have a look, I am not sure how to do that I'll read up on it

**Comment by sakshipuranik23** [comment]
Solved by #6

**Comment by Prathamesh-Shanbhag** [comment]
All my Contributions are done but I can help more, with bug fixes
